server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

photoPrinter:
  clientId: springsecurity
  clientSecret: Teno2019
  grantType: authorization_code
  userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
  accessTokenUri: http://localhost:8090/auth/oauth/token
  redirectUri: http://localhost:8080/redirect     
  userInfoUri: http://localhost:8090/auth/user
  photoResourceUri: http://localhost:9000/photos
  photoWithMetaResourceUri: http://localhost:9000/photos-with-meta