server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

photoPrinter:
  clientId: photo-printer
  clientSecret: 1234
  grantType: authorization_code
  userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
  accessTokenUri: http://localhost:8090/auth/oauth/token
  redirectUri: http://localhost:8080/redirect     
  tokenIntrospectUri: http://localhost:8090/auth/oauth/check_token
  photoResourceUri: http://localhost:9000/photos
  photoWithMetaResourceUri: http://localhost:9000/photos-with-meta